name: charge_points
description: A Charge Points client dart wrapper. For more information about API, go to https://openchargemap.org/site/develop/api#/
version: 1.0.0
repository: https://github.com/Enrico724/charge_points

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
